theme: jekyll-theme-minimal

logo: THF_Roundel_whitecentre.png

title: Health Foundation Analytics Lab
description: "Resources and code: "

baseurl: 
url: 

# Google Analytics
google_analytics: G-9WTK7S5JYD
